### ISSUE TITLE
Unrecognized symbols cmH2O and inH2O

### ISSUE THREAD

**Issue by kaer** [gentooboontoo/js-quantities#33]
Hi, I was testing some all the units of some measurements and found some symbols that didn't work.

- the symbols "cmH2O" and "inH2O" (pressure units) are not recognized
- when using the grain symbol "gr" to any mass unit an incompatible unit exception is thrown

**Comment by gentooboontoo** [comment]
Internally parsed as `cmH cmH O` which is obviously wrong.

**Comment by gentooboontoo** [comment]
Fixed by PR #51.

**Comment by Matthijn** [comment]
Seems:

"when using the grain symbol "gr" to any mass unit an incompatible unit exception is thrown"

is still happening.

**Comment by gentooboontoo** [comment]
A separate issue is opened (#39).
